apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "coffee-shop-backend.fullname" . }}-supply-balance
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: supply-balance
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              {{- if $.Values.cronjob.cmd }}
              command:
                {{  range .Values.cronjob.cmd }}
                  - {{ . }}
                {{ end }}
              {{- end }}
              envFrom:
                - secretRef:
                    name: {{ include "coffee-shop-backend.fullname" . }}-secret
          restartPolicy: OnFailure






          