apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coffee-shop-backend.fullname" . }}-secret
  labels:
    {{- include "coffee-shop-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $filePath := .Values.envfile }}
  {{- with .Files.Get $filePath }}
  {{ . | nindent 2 }}
  {{- end }}