{{- if .Values.secrettls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coffee-shop-frontend.fullname" . }}-tls
  labels:
    {{- include "coffee-shop-frontend.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrettls.crt | b64enc }}
  tls.key: {{ .Values.secrettls.key | b64enc }}
{{- end }}